// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace MGameplayTags
{
	/* Input Tags */
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ctrl);
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Shop);
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_GameplayMenu);
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Shift);
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Held);
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Confirm);
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Cancel);

	/* State Tags */
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Stun);
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Health_Empty);
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Aim);
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Crosshair);

	/* Gameplay Ability Tags */
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_BasicAttack)
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_BasicAttack_Pressed)
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_BasicAttack_Released)
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_One);
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Two);
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Three);
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Four);
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combo);
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combo_Damage);
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dash);
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dash_Start);
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Passive_Launch_Activate);
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Shoot);
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_AOE);

	/* Role Tags */
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Hero);

	/* Attr Tags */
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attr_Experience);
	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attr_Gold);

	MOBA_PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Target_Updated);
}

